### PR TITLE
Added PID acceptance in the B0 for pions, kaons, photons, and Pi0 for…

### PR DESCRIPTION
**Pull request by ajentsch**
… the D&T group rapidity gap studies.

I just added "AddParticle" calls to the B0 to include pions, kaons, photons, and pi0 for the D&T group.

### CODE REVIEW

**Comment by kkauder** [comment]
Mostly for work flow training, I updated the README. You see that changes can still be made by you or others during this PR review. I'm assuming you have no complaints, but please tell me whether you're okay with this change before I merge.

**Review by ajentsch — COMMENTED** [review]
This all looks good. Some further discussion: in principle all charged particles would register in the B0 sensors. Additionally, we have discussed an EMCAL or preshower in the B0 system as well for photons et al. This acceptance addition is to get a rough idea of these additional particle acceptances.

**Comment by kkauder** [comment]
Ok, it's merged now and I deleted the branch. You now want to
- update your local repo
git checkout master
git pull
- delete the branch locally, easiest is
git fetch --all --prune

**Comment by kkauder** [comment]
Oh, and I updated on the cluster too. Should propagate in a few minutes.

**Pull request merged**
